Fatima: School grading system
gymshark/gsauto-training-course pull request #14
Opened 2024-05-23 10:33 UTC by FatimaFarah93

I've created the if statements around each score range to ensure that it prints the correct grade for each one.

2024-05-24 11:33 UTC, owynowyn commented on src/main/java/session2conditionals/SchoolGradingSystemFatima.java
> +        } else if (score > 60 && score < 70) {
Tiny changes to make I think:
The condition score > 60 && score < 70 should be score >= 60 && score < 70 to include scores of 60.

2024-05-24 11:34 UTC, owynowyn commented on src/main/java/session2conditionals/SchoolGradingSystemFatima.java
> +
You may also want to add a small check here to make sure the score is within bounds:

> // Validate the score is within the 0-100 range
>         if (score < 0 || score > 100) {
>             throw new IndexOutOfBoundsException("Invalid Scoring range, Please enter a score between 0 and 100");
>         }

2024-05-24 11:34 UTC, owynowyn commented on src/main/java/session2conditionals/SchoolGradingSystemFatima.java
> +
Before you then proceed to do your actual if statement checks

2024-05-24 11:35 UTC, owynowyn submitted a review, later dismissed
Great work again, couple of tiny changes to make :D

2024-05-24 11:36 UTC, owynowyn requested changes
Great work again! Tiny changes to make :D

2024-05-24 11:58 UTC, FatimaFarah93 reviewed
I've added in the changes requested:
1. The >= to include 60 into the D category
2. The invalid score message

2024-05-30 07:16 UTC, dwilliams-gs approved these changes
Looks good to me. Nice work @FatimaFarah93 🥳

2024-05-30 07:16 UTC, merged