Fatima: string manipulation and formatting
gymshark/gsauto-training-course pull request #31
Opened 2024-06-05 13:20 UTC by FatimaFarah93

I've completed the steps to the exercise by creating String methods, printing out a statement that states that part of the username and name is the same through removing the dot and using the ignoreCase method. I've used String Builder and also printed out a statement using String formatting.

2024-06-07 14:24 UTC, owynowyn commented on src/main/java/session5strings/StringManipulationAndFormattingFatima.java
> +        System.out.printf("Email is is %s, Username is %s, the name is %s. Is username and name the same: %b"
Here you could use the StringBuilder you created on line 23 as it looks like that is actually unused. I see how you've formatted it using the %s etc. replacements, an alternative could be to just add the nicely formatted texts to your `message.append` code. E.g.

> message.append("Email: ").append(emailAddress).append("\n");
> message.append("Username: ").append(username).append("\n");
> message.append("Name in Uppercase: ").append(upperCaseName).append("\n");
> message.append("Does the username match the name (ignoring case): ").append(isUserNameEqualToName);

2024-06-07 14:24 UTC, owynowyn commented on src/main/java/session5strings/StringManipulationAndFormattingFatima.java
> +import java.util.function.ToDoubleBiFunction;
Unused import here that we could probably clear out

2024-06-07 14:25 UTC, owynowyn requested changes
Minor changes to formatting required, great work again though 🙏

2024-06-10 10:15 UTC, FatimaFarah93 commented
Pushed up the changes around printing the string builder and removing the unusued import @owynowyn

2024-06-10 16:01 UTC, owynowyn approved these changes
Looks good to me!

2024-06-10 16:01 UTC, merged