Fatima:Library Book
gymshark/gsauto-training-course pull request #32
Opened 2024-06-06 13:20 UTC by FatimaFarah93

Completed exercise around the library book by creating a Book class and following the steps.

2024-06-07 14:29 UTC, owynowyn commented on src/main/java/session6classes/LibraryBookFatima.java
> +    public static class Book {
I think you could remove this entire line and the closing `}` on line 26 and just have all the code within the `LibraryBookFatima` class. May need to rename the constructor too and the instantiations in the main method

2024-06-07 14:30 UTC, owynowyn commented on src/main/java/session6classes/LibraryBookFatima.java
> +    public static class Book {
Summed up, I dont think the internal static class is essential and I think it should be fine to just have your `LibraryBookFatima` class with all the code within it

2024-06-07 14:31 UTC, owynowyn approved these changes

2024-06-07 14:32 UTC, owynowyn requested changes
Again, minor changes to make as I dont think the internal class is necessary. Let me know if you want to run through anything or need any assistance with it! Great work again though!

2024-06-10 09:22 UTC, FatimaFarah93 commented
Hi @owynowyn I've made the changes and moved the code into the internal class, should be in the latest version of the branch as I've pushed it all up now

2024-06-10 16:03 UTC, owynowyn approved these changes
Great work again Fatima

2024-06-10 16:03 UTC, merged