Fatima: Company Worker System
gymshark/gsauto-training-course pull request #51
Opened 2024-06-20 13:17 UTC by FatimaFarah93

Created abstract class workerFatima and subclasses for office worker, factory worker and remote worker and implemented abstract methods. Created a main class to execute the code.

2024-06-24 11:05 UTC, owynowyn commented on src/main/java/session9inheritanceabstract/taskentries/FactoryWorkerFatima.java
> +    void work() {
Could maybe add the @Override tag here to clarify this is an overridden method

2024-06-24 11:05 UTC, owynowyn commented on src/main/java/session9inheritanceabstract/taskentries/FactoryWorkerFatima.java
> +    void takeBreak() {
Could maybe add the @Override tag here to clarify this is an overridden method

2024-06-24 11:05 UTC, owynowyn commented on src/main/java/session9inheritanceabstract/taskentries/FactoryWorkerFatima.java
> +    void takeBreak() {
Same on the other classes methods actually

2024-06-24 11:06 UTC, owynowyn requested changes
Great work Fatima, not an essential change to make but adding the @Override tag to your methods will really help someone else see that these methods are overridden from a parent class. Again, not major but hopefully just a quick change to make 👍 🟢

2024-06-24 13:27 UTC, FatimaFarah93 commented
Hey @owynowyn just added override to the worker java classes in the latest commit.

2024-07-01 08:59 UTC, owynowyn approved these changes
Great work Fatima!

2024-07-01 08:59 UTC, merged