Fatima: Interface task
gymshark/gsauto-training-course pull request #57
Opened 2024-06-28 14:58 UTC by FatimaFarah93

Created interface for electronic device alongside classes that implemented the methods.

2024-07-01 09:04 UTC, owynowyn commented on src/main/java/session11/LampFatima.java
> +        if (isOn()) {
Logic Correction in turnOn and turnOff Methods:
The logic in your turnOn and turnOff methods is reversed. The turnOn method should check if the lamp is off before turning it on, and vice versa for the turnOff method.

2024-07-01 09:04 UTC, owynowyn commented on src/main/java/session11/LampFatima.java
> +        if (isOn()) {
Same for the other classes I believe, easy mistake to make

2024-07-01 09:07 UTC, owynowyn commented on src/main/java/session11/LampFatima.java
> +        return false;
State Management:
Currently, the isOn method always returns `false`, indicating that the lamp is always off. You should maintain a state variable to track whether the lamp is on or off.

`private boolean isOn = false;` as a field at the top of each class to begin with, then in your methods you could set `isOn` to true/false accordingly;

> @Override
>     public void turnOff() {
>         if (isOn()) {
>             System.out.println("The Lamp is now off");
>             isOn = false;
>         } else {
>            System.out.println("The lamp is already off");
>         }
>     }

2024-07-01 09:08 UTC, owynowyn commented on src/main/java/session11/LampFatima.java
> +        return false;
and then the isOn method can just return the field

2024-07-01 09:08 UTC, owynowyn commented on src/main/java/session11/LampFatima.java
> +        return false;
Again, same for the other classes

2024-07-01 09:09 UTC, owynowyn requested changes
Great work again, just some slight changes to make to the logic of each class, give me a shout if you need any guidance!

2024-07-01 14:16 UTC, FatimaFarah93 commented
I've made the changes and pushed them up to the latest build @owynowyn

2024-07-03 09:48 UTC, owynowyn commented on src/main/java/session11/TelevisionFatima.java
> +    public void turnOff() {
Logical Errors in turnOff Method:
It looks like this method is intended to turn the television off if it was currently on. However, the code is actually turning the television on instead of off.
The message "The television is now on" was being printed when the television was being turned off, which is incorrect.
If the television is already off, the message "The television is already on" is printed, which is also incorrect.

2024-07-03 09:49 UTC, owynowyn commented on src/main/java/session11/TelevisionFatima.java
> +    public void turnOff() {
I think its the same for the other methods in the other classes too

2024-07-03 09:51 UTC, owynowyn commented on src/main/java/session11/TelevisionFatima.java
> +            isOn = false;
I think you would just need to update these 2 lines in each of the methods to be fair; `if !isOn (meaning it the tv is off, and you perform the turnOn method, you want isOn=true`)

2024-07-08 14:54 UTC, owynowyn approved these changes
Great work! ✅

2024-07-08 14:54 UTC, merged