Fatima: Boxer Task
gymshark/gsauto-training-course pull request #62
Opened 2024-07-01 11:31 UTC by FatimaFarah93

PR is ready!

2024-07-01 11:41 UTC, owynowyn commented on src/main/java/javafundamentalsboxertask/BoxerTaskFatima.java
> +            if ((random.nextInt() % 5) == 0) {
Rather than using multiple random.nextInt here and on line 20, you could just use the same one to ensure consistency as you will essentially generate 2 different random numbers on each of those lines.

```
for (int i = 0; i < playerPunches.length; i++) {
    playerPunches[i] = random.nextInt(100) + 1; // Punch strength between 1 and 100
}
```

2024-07-01 11:43 UTC, owynowyn commented on src/main/java/javafundamentalsboxertask/BoxerTaskFatima.java
> +            if ((random.nextInt() % 5) == 0) {
Also the check `if ((random.nextInt() % 5) == 0)` incorrectly uses random.nextInt() without specifying a bound, which can result in unexpected negative values.

2024-07-01 11:48 UTC, owynowyn commented on src/main/java/javafundamentalsboxertask/BoxerTaskFatima.java
> +            System.exit(0);
You should be able to just simply break; out of this condition to finish the program

2024-07-01 11:49 UTC, owynowyn requested changes
Great first attempt Fatima! Some slight changes to logic required, give me a shout if you need any help

2024-07-01 15:40 UTC, FatimaFarah93 commented
I've made the changes requested and pushed it to the latest build. I added some additional logic to the last if statement as the loop would not break if boxerhealth ==0, so i included additional logic to capture anything lower than 0 as in some instances the double punches would go straight into the negatives

2024-07-03 10:05 UTC, owynowyn commented on src/main/java/javafundamentalsboxertask/BoxerTaskFatima.java
> +            if (boxerHealthPoints > 0) {
I would probably move this if statement outside of the loop, as at the moment it is being called for every iteration

2024-07-03 10:06 UTC, owynowyn commented on src/main/java/javafundamentalsboxertask/BoxerTaskFatima.java
> +            } else if ((boxerHealthPoints == 0) || (boxerHealthPoints < 0)) {
You could simplify this to `boxerHealthPoints <= 0` rather than the 2 separate conditions

2024-07-03 10:07 UTC, owynowyn commented on src/main/java/javafundamentalsboxertask/BoxerTaskFatima.java
> +            } else if ((boxerHealthPoints == 0) || (boxerHealthPoints < 0)) {
And I would recommend keeping this else if portion of the if statement, within the loop, so that if its a knockout before the 100 punches and you break out of the loop with a `break;`, the loop will end

2024-07-03 10:09 UTC, owynowyn commented on src/main/java/javafundamentalsboxertask/BoxerTaskFatima.java
> +            System.out.println("Punch Strength:" + random.nextInt(100));
`random.nextInt(100)` in this line will generate a new random number, so I would replace that with punchStrength, as that is what is used throughout this loop.

2024-07-18 09:29 UTC, owynowyn approved these changes
Great work Fatima!

2024-07-18 09:29 UTC, merged