Enums Task Maria
gymshark/gsauto-training-course pull request #72
Opened 2024-07-04 17:03 UTC by mariastephan2186

Enums task done

2024-07-05 10:49 UTC, owynowyn commented on src/main/java/session13enums/examples/DirectionsTask_Maria.java
> +        DirectionsTask_Maria east = DirectionsTask_Maria.EAST;
You could try calling this in a loop using the `DirectionsTask_Maria.values()` method and looping through the array

2024-07-05 10:50 UTC, owynowyn requested changes
Nice work, exactly what we were looking for but again, for an additional task, try looping through the built-in method

2024-07-05 12:40 UTC, mariastephan2186 commented
@owynowyn Made the changes to the task - added a loop through using the Values method.

2024-07-08 14:49 UTC, owynowyn approved these changes
Perfect! ✅

2024-07-08 14:49 UTC, merged