BDD Exercise_Maria
gymshark/gsauto-training-course pull request #76
Opened 2024-07-10 11:29 UTC by mariastephan2186

BDD Exercise Task - done

2024-07-18 10:59 UTC, owynowyn commented on src/main/java/session14bddgherkin/examples/Wishlist.feature
> +  And the user confirms the addition when prompted
You could probably remove this step, as it will be implied from the previous step anyway 👍

2024-07-18 11:00 UTC, owynowyn commented on src/main/java/session14bddgherkin/examples/Wishlist.feature
> +    And the user receives  a confirmation message that the item has been successfully added
You could also remove this step, as again, this would be implied with the above, although, I wouldn't argue against having this one in as it still feels quite behavioural

2024-07-18 11:01 UTC, owynowyn requested changes
Nice work, could maybe remove 1 or 2 steps for the same result!

2024-07-30 08:18 UTC, owynowyn commented on src/main/java/session14bddgherkin/examples/Wishlist.feature
> +    And the user receives  a confirmation message that the item has been successfully added
Remember to remove this one @mariastephan2186

2024-07-30 14:16 UTC, mariastephan2186 commented
Removed and changed last step lightly @owynowyn

2024-08-01 15:12 UTC, owynowyn approved these changes
Lovely 😄

2024-08-01 15:12 UTC, merged