Fatima: Wait task
gymshark/gsauto-training-course pull request #81
Opened 2024-07-18 15:12 UTC by FatimaFarah93

PR is ready for review!

2024-07-22 09:16 UTC, owynowyn commented on src/main/java/session17waitsandsync/examples/fatima/implicitWait.java
> +        WebDriver driver = new ChromeDriver();
`driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));` to set an implicit wait, after the driver has been set up that is.

2024-07-22 09:17 UTC, owynowyn commented on src/main/java/session17waitsandsync/examples/fatima/implicitWait.java
> +        WebDriver driver = new ChromeDriver();
That will then implicitly wait every time you interact with the driver, so you won't need to do anything else after the above line of code has been added - https://www.selenium.dev/documentation/webdriver/waits/

2024-07-22 09:18 UTC, owynowyn requested changes
1 small change to add but it is pretty much there! 💯

2024-07-23 15:21 UTC, FatimaFarah93 commented
I've done that change now :)

2024-07-30 08:20 UTC, owynowyn approved these changes
Great work!

2024-07-30 08:20 UTC, merged